In [19]:
years = list(range(2003, 2024))

In [20]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

In [21]:
import requests

# for year in years:
#     url = url_start.format(year)
#     data = requests.get(url)
    
    
#     with open("roy/{}.html".format(year), "w+",  encoding="utf-8") as f:
#         f.write(data.text)

In [22]:
from bs4 import BeautifulSoup

In [23]:
with open("roy/2003.html", encoding="utf-8") as f:
    page = f.read()

In [24]:
soup = BeautifulSoup(page, "html.parser")

In [25]:
soup.find('tr', class_="over_header").decompose()

In [26]:
soup.find('tr', class_="over_header").decompose()

In [27]:
roy_table = soup.find_all(id="roy")

In [28]:
import pandas as pd

In [29]:
roy_2003 = pd.read_html(str(roy_table))[0]

In [30]:
roy_2003

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Amar'e Stoudemire,20,PHO,59.0,458.0,585,0.783,82,31.3,13.5,8.8,1.0,0.8,1.1,0.472,0.200,0.661,6.2,0.116
1,2,Yao Ming,22,HOU,45.0,405.0,585,0.692,82,29.0,13.5,8.2,1.7,0.4,1.8,0.498,0.500,0.811,8.7,0.176
2,3,Caron Butler,22,MIA,13.0,179.0,585,0.306,78,36.6,15.4,5.1,2.7,1.8,0.4,0.416,0.318,0.824,5.1,0.086
3,4,Manu Ginóbili,25,SAS,0.0,5.0,585,0.009,69,20.7,7.6,2.3,2.0,1.4,0.2,0.438,0.345,0.737,4.2,0.141
4,5,Drew Gooden,21,TOT,0.0,3.0,585,0.005,70,26.8,12.5,6.5,1.2,0.8,0.5,0.457,0.292,0.712,1.7,0.043
5,6,Nenê,20,DEN,0.0,2.0,585,0.003,80,28.2,10.5,6.1,1.9,1.6,0.8,0.519,0.000,0.578,5.0,0.107
6,7,Carlos Boozer,21,CLE,0.0,1.0,585,0.002,81,25.3,10.0,7.5,1.3,0.7,0.6,0.536,0.000,0.771,5.9,0.139

In [31]:
dfs = []
for year in years:
    with open("roy/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_="over_header").decompose()
    soup.find('tr', class_="over_header").decompose()
    roy_table = soup.find_all(id="roy")
    roy = pd.read_html(str(roy_table))[0]
    roy["Year"] = year
    
    dfs.append(roy)

In [32]:
dfs

[   Rank             Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0     1  Amar'e Stoudemire   20  PHO   59.0    458.0      585  0.783  82
 1     2           Yao Ming   22  HOU   45.0    405.0      585  0.692  82
 2     3       Caron Butler   22  MIA   13.0    179.0      585  0.306  78
 3     4      Manu Ginóbili   25  SAS    0.0      5.0      585  0.009  69
 4     5        Drew Gooden   21  TOT    0.0      3.0      585  0.005  70
 5     6               Nenê   20  DEN    0.0      2.0      585  0.003  80
 6     7      Carlos Boozer   21  CLE    0.0      1.0      585  0.002  81

      MP  ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  31.3  ...  8.8  1.0  0.8  1.1  0.472  0.200  0.661  6.2  0.116  2003
 1  29.0  ...  8.2  1.7  0.4  1.8  0.498  0.500  0.811  8.7  0.176  2003
 2  36.6  ...  5.1  2.7  1.8  0.4  0.416  0.318  0.824  5.1  0.086  2003
 3  20.7  ...  2.3  2.0  1.4  0.2  0.438  0.345  0.737  4.2  0.141  2003
 4  26.8  ...  6.5  1.2  0.8  0.5  0.457  0.292  0.712  1.7  0.043  2003
 5  28.2  ...  6.1  1.9  1.6  0.8  0.519  0.000  0.578  5.0  0.107  2003
 6  25.3  ...  7.5  1.3  0.7  0.6  0.536  0.000  0.771  5.9  0.139  2003

 [7 rows x 21 columns],
    Rank           Player  Age   Tm  First  Pts Won  Pts Max  Share   G    MP  \
 0     1     LeBron James   19  CLE   78.0    508.0      590  0.861  79  39.5
 1     2  Carmelo Anthony   19  DEN   40.0    430.0      590  0.729  82  36.5
 2     3      Dwyane Wade   22  MIA    0.0    117.0      590  0.198  61  34.9
 3     4     Kirk Hinrich   23  CHI    0.0      4.0      590  0.007  76  35.6
 4     5       Chris Bosh   19  TOR    0.0      2.0      590  0.003  75  33.5
 5     6  Marquis Daniels   23  DAL    0.0      1.0      590  0.002  56  18.6

    ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  ...  5.5  5.9  1.6  0.7  0.417  0.290  0.754  5.1  0.078  2004
 1  ...  6.1  2.8  1.2  0.5  0.426  0.322  0.777  6.1  0.098  2004
 2  ...  4.0  4.5  1.4  0.6  0.465  0.302  0.747  4.6  0.103  2004
 3  ...  3.4  6.8  1.3  0.3  0.386  0.390  0.804  4.1  0.072  2004
 4  ...  7.4  1.0  0.8  1.4  0.459  0.357  0.701  6.2  0.119  2004
 5  ...  2.6  2.1  0.9  0.2  0.494  0.306  0.769  3.2  0.146  2004

 [6 rows x 21 columns],
   Rank          Player  Age   Tm  First  Pts Won  Pts Max  Share   G    MP  \
 0    1    Emeka Okafor   22  CHA   77.0    514.0      630  0.816  73  35.6
 1    2      Ben Gordon   21  CHI   43.0    443.0      630  0.703  82  24.4
 2    3   Dwight Howard   19  ORL    6.0    161.0      630  0.256  82  32.6
 3    4  Andre Iguodala   21  PHI    0.0     14.0      630  0.022  82  32.8
 4   5T       Luol Deng   19  CHI    0.0      1.0      630  0.002  61  27.3
 5   5T      J.R. Smith   19  NOH    0.0      1.0      630  0.002  76  24.5

    ...   TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  ...  10.9  0.9  0.8  1.7  0.447  0.000  0.609  4.0  0.074  2005
 1  ...   2.6  2.0  0.6  0.1  0.411  0.405  0.863  3.5  0.084  2005
 2  ...  10.0  0.9  0.9  1.7  0.520  0.000  0.671  7.3  0.131  2005
 3  ...   5.7  3.0  1.7  0.6  0.493  0.331  0.743  6.6  0.118  2005
 4  ...   5.3  2.2  0.8  0.4  0.434  0.265  0.741  3.0  0.086  2005
 5  ...   2.0  1.9  0.7  0.1  0.394  0.288  0.689  0.2  0.006  2005

 [6 rows x 21 columns],
   Rank              Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0    1          Chris Paul   20  NOK  124.0    623.0      625  0.997  78
 1    2  Charlie Villanueva   21  TOR    0.0    248.0      625  0.397  81
 2    3        Andrew Bogut   21  MIL    0.0     98.0      625  0.157  82
 3    4      Raymond Felton   21  CHA    0.0     79.0      625  0.126  80
 4    5       Channing Frye   22  NYK    0.0     41.0      625  0.066  65
 5    6      Deron Williams   21  UTA    1.0     31.0      625  0.050  80
 6   7T       Danny Granger   22  IND    0.0      2.0      625  0.003  78
 7   7T         Luther Head   23  HOU    0.0      2.0      625  0.003  80
 8    9          Ryan Gomes   23  BOS    0.0      1.0      625  0.002  61

      MP  ...  TRB  AST  STL  BLK    FG%    3P%    FT%    WS  WS/48  Year
 0  36.0  ...  5.1  7.8  2.2  0.1  0.430  0.282  0.847  10.4  0.178  2006
 1  29.1  ...  6.4  1.1  0.7  0.8  0.463  0.327  0.706   3.9  0.079  2006
 2  28.6  ...  7.0  2.3  0.6  0.8  0.533  0.000  0.629   5.5  0.113  2006
 3  30.1  ...  3.3  5.6  1.3  0.1  0.391  0.358  0.725   2.6  0.051  2006
 4  24.2  ...  5.8  0.8  0.5  0.7  0.477  0.333  0.825   3.5  0.108  2006
 5  28.8  ...  2.4  4.5  0.8  0.2  0.421  0.416  0.704   2.8  0.059  2006
 6  22.6  ...  4.9  1.2  0.7  0.8  0.462  0.323  0.777   5.1  0.139  2006
 7  28.9  ...  3.3  2.7  1.1  0.1  0.403  0.361  0.699   3.5  0.072  2006
 8  22.6  ...  4.9  1.0  0.6  0.1  0.487  0.333  0.752   3.1  0.108  2006

 [9 rows x 21 columns],
     Rank             Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0      1        Brandon Roy   22  POR  127.0    638.0      640  0.997  57
 1      2    Andrea Bargnani   21  TOR    1.0    264.0      640  0.413  65
 2      3           Rudy Gay   20  MEM    0.0     93.0      640  0.145  78
 3      4      Adam Morrison   22  CHA    0.0     44.0      640  0.069  78
 4      5         Randy Foye   23  MIN    0.0     37.0      640  0.058  82
 5      6       Paul Millsap   21  UTA    0.0     19.0      640  0.030  82
 6      7  LaMarcus Aldridge   21  POR    0.0     18.0      640  0.028  63
 7      8    Jorge Garbajosa   29  TOR    0.0     17.0      640  0.027  67
 8      9       Tyrus Thomas   20  CHI    0.0     10.0      640  0.016  72
 9     10    Walter Herrmann   27  CHA    0.0      5.0      640  0.008  48
 10    11        Craig Smith   23  MIN    0.0      4.0      640  0.006  82
 11    12        Rajon Rondo   20  BOS    0.0      3.0      640  0.005  78

       MP  ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0   35.4  ...  4.4  4.0  1.2  0.2  0.456  0.377  0.838  4.8  0.114  2007
 1   25.1  ...  3.9  0.8  0.5  0.8  0.427  0.373  0.824  1.9  0.057  2007
 2   27.0  ...  4.5  1.3  0.9  0.9  0.422  0.364  0.727  0.5  0.011  2007
 3   29.8  ...  2.9  2.1  0.4  0.1  0.376  0.337  0.710 -1.5 -0.030  2007
 4   22.9  ...  2.7  2.8  0.6  0.3  0.434  0.368  0.854  2.3  0.058  2007
 5   18.0  ...  5.2  0.8  0.8  0.9  0.525  0.333  0.673  4.7  0.153  2007
 6   22.1  ...  5.0  0.4  0.3  1.2  0.503  0.000  0.722  3.4  0.118  2007
 7   28.5  ...  4.9  1.9  1.2  0.2  0.420  0.342  0.731  3.0  0.074  2007
 8   13.4  ...  3.7  0.6  0.6  1.1  0.475  0.000  0.606  2.2  0.110  2007
 9   19.5  ...  2.9  0.5  0.4  0.1  0.527  0.461  0.774  2.4  0.125  2007
 10  18.7  ...  5.1  0.6  0.6  0.2  0.531  0.000  0.624  3.9  0.121  2007
 11  23.5  ...  3.7  3.8  1.6  0.1  0.418  0.207  0.647  2.4  0.064  2007

 [12 rows x 21 columns],
   Rank               Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0    1         Kevin Durant   19  SEA   90.0    545.0      625  0.872  80
 1    2           Al Horford   21  ATL   30.0    390.0      625  0.624  81
 2    3           Luis Scola   27  HOU    5.0    146.0      625  0.234  82
 3    4          Al Thornton   24  LAC    0.0     30.0      625  0.048  79
 4    5         Jamario Moon   27  TOR    0.0      7.0      625  0.011  78
 5    6  Juan Carlos Navarro   27  MEM    0.0      3.0      625  0.005  82
 6    7       Thaddeus Young   19  PHI    0.0      2.0      625  0.003  74
 7   8T          Mike Conley   20  MEM    0.0      1.0      625  0.002  53
 8   8T          Carl Landry   24  HOU    0.0      1.0      625  0.002  42

      MP  ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  34.6  ...  4.4  2.4  1.0  0.9  0.430  0.288  0.873  2.3  0.040  2008
 1  31.4  ...  9.7  1.5  0.7  0.9  0.499  0.000  0.731  5.5  0.103  2008
 2  24.7  ...  6.4  1.3  0.7  0.2  0.515  0.000  0.668  6.5  0.154  2008
 3  27.3  ...  4.5  1.2  0.6  0.5  0.429  0.331  0.743  1.1  0.025  2008
 4  27.8  ...  6.2  1.2  1.0  1.4  0.485  0.328  0.741  5.7  0.126  2008
 5  25.8  ...  2.6  2.2  0.6  0.0  0.402  0.361  0.849  1.4  0.031  2008
 6  21.0  ...  4.2  0.8  1.0  0.1  0.539  0.316  0.738  4.5  0.140  2008
 7  26.1  ...  2.6  4.2  0.8  0.0  0.428  0.330  0.732  1.1  0.038  2008
 8  16.9  ...  4.9  0.5  0.4  0.2  0.616  0.000  0.661  3.7  0.251  2008

 [9 rows x 21 columns],
    Rank             Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0     1       Derrick Rose   20  CHI  111.0    574.0      600  0.957  81
 1     2          O.J. Mayo   21  MEM    5.0    246.0      600  0.410  82
 2     3        Brook Lopez   20  NJN    2.0    127.0      600  0.212  82
 3     4  Russell Westbrook   20  OKC    2.0     73.0      600  0.122  82
 4     5        Eric Gordon   20  LAC    0.0     22.0      600  0.037  78
 5     6         Kevin Love   20  MIN    0.0     16.0      600  0.027  81
 6     7    Michael Beasley   20  MIA    0.0      7.0      600  0.012  81
 7     8         Marc Gasol   24  MEM    0.0      4.0      600  0.007  82
 8    9T     Rudy Fernández   23  POR    0.0      3.0      600  0.005  78
 9    9T        Robin Lopez   20  PHO    0.0      3.0      600  0.005  60
 10  11T     Mario Chalmers   22  MIA    0.0      2.0      600  0.003  82
 11  11T       Courtney Lee   23  ORL    0.0      2.0      600  0.003  77
 12   13      Nicolas Batum   20  POR    0.0      1.0      600  0.002  79

       MP  ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0   37.0  ...  3.9  6.3  0.8  0.2  0.475  0.222  0.788  4.9  0.078  2009
 1   38.0  ...  3.8  3.2  1.1  0.2  0.438  0.384  0.879  3.4  0.052  2009
 2   30.5  ...  8.1  1.0  0.5  1.8  0.531  0.000  0.793  5.8  0.112  2009
 3   32.5  ...  4.9  5.3  1.3  0.2  0.398  0.271  0.815  1.9  0.035  2009
 4   34.3  ...  2.6  2.8  1.0  0.4  0.456  0.389  0.854  4.6  0.082  2009
 5   25.3  ...  9.1  1.0  0.4  0.6  0.459  0.105  0.789  5.3  0.124  2009
 6   24.8  ...  5.4  1.0  0.5  0.5  0.472  0.407  0.772  3.4  0.081  2009
 7   30.7  ...  7.4  1.7  0.8  1.1  0.530  0.000  0.733  6.4  0.121  2009
 8   25.6  ...  2.7  2.0  0.9  0.2  0.425  0.399  0.839  6.1  0.147  2009
 9   10.2  ...  2.0  0.1  0.2  0.7  0.518  0.000  0.691  1.1  0.083  2009
 10  32.0  ...  2.8  4.9  2.0  0.1  0.420  0.367  0.767  5.2  0.095  2009
 11  25.2  ...  2.3  1.2  1.0  0.2  0.450  0.404  0.830  4.4  0.108  2009
 12  18.4  ...  2.8  0.9  0.6  0.5  0.446  0.369  0.808  3.7  0.123  2009

 [13 rows x 21 columns],
   Rank            Player  Age   Tm  First  Pts Won  Pts Max  Share   G    MP  \
 0    1      Tyreke Evans   20  SAC   67.0    491.0      615  0.798  72  37.2
 1    2     Stephen Curry   21  GSW   43.0    391.0      615  0.636  80  36.2
 2    3  Brandon Jennings   20  MIL   12.0    204.0      615  0.332  82  32.6
 3    4   Darren Collison   22  NOH    1.0     17.0      615  0.028  76  27.8
 4   5T       Jonny Flynn   20  MIN    0.0      2.0      615  0.003  81  28.9
 5   5T        Taj Gibson   24  CHI    0.0      2.0      615  0.003  82  26.9

    ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  ...  5.3  5.8  1.5  0.4  0.458  0.255  0.748  5.4  0.097  2010
 1  ...  4.5  5.9  1.9  0.2  0.462  0.437  0.885  4.7  0.077  2010
 2  ...  3.4  5.7  1.3  0.2  0.371  0.374  0.817  4.2  0.075  2010
 3  ...  2.5  5.7  1.0  0.1  0.477  0.400  0.851  2.9  0.067  2010
 4  ...  2.4  4.4  1.0  0.0  0.417  0.358  0.826  0.1  0.002  2010
 5  ...  7.5  0.9  0.6  1.3  0.494    NaN  0.646  4.7  0.103  2010

 [6 rows x 21 columns],
    Rank            Player  Age   Tm  First  Pts Won  Pts Max  Share   G    MP  \
 0     1     Blake Griffin   21  LAC  118.0    590.0      590  1.000  82  38.0
 1     2         John Wall   20  WAS    0.0    295.0      590  0.500  69  37.8
 2     3  DeMarcus Cousins   20  SAC    0.0     81.0      590  0.137  81  28.5
 3     4     Landry Fields   22  NYK    0.0     62.0      590  0.105  82  31.0
 4     5         Gary Neal   26  SAS    0.0     19.0      590  0.032  80  21.1
 5     6       Greg Monroe   20  DET    0.0     15.0      590  0.025  80  27.8

    ...   TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  ...  12.1  3.8  0.8  0.5  0.506  0.292  0.642  9.8  0.152  2011
 1  ...   4.6  8.3  1.8  0.5  0.409  0.296  0.766  2.2  0.041  2011
 2  ...   8.6  2.5  1.0  0.8  0.430  0.167  0.687  1.1  0.022  2011
 3  ...   6.4  1.9  1.0  0.2  0.497  0.393  0.769  5.3  0.100  2011
 4  ...   2.5  1.2  0.3  0.1  0.451  0.419  0.808  3.5  0.099  2011
 5  ...   7.5  1.3  1.2  0.6  0.551  0.000  0.622  6.6  0.143  2011

 [6 rows x 21 columns],
     Rank            Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0      1      Kyrie Irving   19  CLE  117.0    592.0      600  0.987  51
 1      2       Ricky Rubio   21  MIN    0.0    170.0      600  0.283  41
 2      3    Kenneth Faried   22  DEN    1.0    129.0      600  0.215  46
 3      4     Kawhi Leonard   20  SAS    1.0     47.0      600  0.078  64
 4      5     Iman Shumpert   21  NYK    1.0     33.0      600  0.055  59
 5      6     Klay Thompson   21  GSW    0.0     30.0      600  0.050  66
 6      7     Isaiah Thomas   22  SAC    0.0     28.0      600  0.047  65
 7      8    Brandon Knight   20  DET    0.0     21.0      600  0.035  66
 8      9  Chandler Parsons   23  HOU    0.0     14.0      600  0.023  63
 9     10    MarShon Brooks   23  NJN    0.0      4.0      600  0.007  56
 10    11      Kemba Walker   21  CHA    0.0      3.0      600  0.005  66
 11    12        Josh Selby   20  MEM    0.0      1.0      600  0.002  28

       MP  ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0   30.5  ...  3.7  5.4  1.1  0.4  0.469  0.399  0.872  4.1  0.125  2012
 1   34.2  ...  4.2  8.2  2.2  0.2  0.357  0.340  0.803  2.0  0.070  2012
 2   22.5  ...  7.7  0.8  0.7  1.0  0.586    NaN  0.665  4.6  0.212  2012
 3   24.0  ...  5.1  1.1  1.3  0.4  0.493  0.376  0.773  5.5  0.171  2012
 4   28.9  ...  3.2  2.8  1.7  0.1  0.401  0.306  0.798  2.4  0.068  2012
 5   24.4  ...  2.4  2.0  0.7  0.3  0.443  0.414  0.868  1.7  0.050  2012
 6   25.5  ...  2.6  4.1  0.8  0.1  0.448  0.379  0.832  4.3  0.124  2012
 7   32.3  ...  3.2  3.8  0.7  0.2  0.415  0.380  0.759  1.3  0.029  2012
 8   28.6  ...  4.8  2.1  1.2  0.5  0.452  0.337  0.551  3.4  0.090  2012
 9   29.4  ...  3.6  2.3  0.9  0.3  0.428  0.313  0.764  0.8  0.022  2012
 10  27.2  ...  3.5  4.4  0.9  0.3  0.366  0.305  0.789  0.3  0.009  2012
 11   8.5  ...  0.5  1.1  0.3  0.0  0.347  0.133  0.786 -0.5 -0.105  2012

 [12 rows x 21 columns],
   Rank                  Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0    1          Damian Lillard   22  POR  121.0    605.0      605  1.000  82
 1    2           Anthony Davis   19  NOH    0.0    306.0      605  0.506  64
 2    3            Bradley Beal   19  WAS    0.0     94.0      605  0.155  56
 3    4          Andre Drummond   19  DET    0.0     36.0      605  0.060  60
 4    5            Dion Waiters   21  CLE    0.0     21.0      605  0.035  61
 5   6T         Harrison Barnes   20  GSW    0.0      8.0      605  0.013  81
 6   6T          Chris Copeland   28  NYK    0.0      8.0      605  0.013  56
 7    8  Michael Kidd-Gilchrist   19  CHA    0.0      3.0      605  0.005  78
 8    9       Jonas Valančiūnas   20  TOR    0.0      2.0      605  0.003  62
 9   10            John Jenkins   21  ATL    0.0      1.0      605  0.002  61

      MP  ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  38.6  ...  3.1  6.5  0.9  0.2  0.429  0.368  0.844  5.8  0.088  2013
 1  28.8  ...  8.2  1.0  1.2  1.8  0.516  0.000  0.751  6.1  0.159  2013
 2  31.2  ...  3.8  2.4  0.9  0.5  0.410  0.386  0.786  3.0  0.082  2013
 3  20.7  ...  7.6  0.5  1.0  1.6  0.608  0.500  0.371  4.5  0.172  2013
 4  28.8  ...  2.4  3.0  1.0  0.3  0.412  0.310  0.746  0.9  0.026  2013
 5  25.4  ...  4.1  1.2  0.6  0.2  0.439  0.359  0.758  2.8  0.065  2013
 6  15.4  ...  2.1  0.5  0.3  0.2  0.479  0.421  0.759  2.1  0.117  2013
 7  26.0  ...  5.8  1.5  0.7  0.9  0.458  0.222  0.749  2.1  0.051  2013
 8  23.9  ...  6.0  0.7  0.3  1.3  0.557    NaN  0.789  3.9  0.127  2013
 9  14.8  ...  1.5  0.9  0.2  0.2  0.446  0.384  0.843  1.7  0.091  2013

 [10 rows x 21 columns],
   Rank                   Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0    1  Michael Carter-Williams   22  PHI  104.0    569.0      620  0.918  70
 1    2           Victor Oladipo   21  ORL   16.0    364.0      620  0.587  80
 2    3               Trey Burke   21  UTA    1.0     96.0      620  0.155  70
 3    4            Mason Plumlee   23  BRK    2.0     58.0      620  0.094  70
 4    5         Tim Hardaway Jr.   21  NYK    1.0     23.0      620  0.037  81
 5    6             Gorgui Dieng   24  MIN    0.0      3.0      620  0.005  60
 6   7T             Steven Adams   20  OKC    0.0      1.0      620  0.002  81
 7   7T    Giannis Antetokounmpo   19  MIL    0.0      1.0      620  0.002  77
 8   7T            Nick Calathes   24  MEM    0.0      1.0      620  0.002  71

      MP  ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  34.5  ...  6.2  6.3  1.9  0.6  0.405  0.264  0.703  1.3  0.026  2014
 1  31.1  ...  4.1  4.1  1.6  0.5  0.419  0.327  0.780  1.3  0.026  2014
 2  32.3  ...  3.0  5.7  0.6  0.1  0.380  0.330  0.903  0.9  0.020  2014
 3  18.2  ...  4.4  0.9  0.7  0.8  0.659  0.000  0.626  4.7  0.176  2014
 4  23.1  ...  1.5  0.8  0.5  0.1  0.428  0.363  0.828  3.1  0.080  2014
 5  13.6  ...  5.0  0.7  0.5  0.8  0.498  1.000  0.634  2.2  0.129  2014
 6  14.8  ...  4.1  0.5  0.5  0.7  0.503    NaN  0.581  2.9  0.114  2014
 7  24.6  ...  4.4  1.9  0.8  0.8  0.414  0.347  0.683  1.2  0.031  2014
 8  16.5  ...  1.9  2.9  0.9  0.1  0.457  0.311  0.611  1.5  0.062  2014

 [9 rows x 21 columns],
    Rank           Player  Age   Tm  First  Pts Won  Pts Max  Share   G    MP  \
 0     1   Andrew Wiggins   19  MIN  110.0    604.0      650  0.929  82  36.2
 1     2   Nikola Mirotić   23  CHI   14.0    335.0      650  0.515  82  20.2
 2     3     Nerlens Noel   20  PHI    3.0    141.0      650  0.217  75  30.8
 3     4    Elfrid Payton   20  ORL    3.0     79.0      650  0.122  82  30.4
 4     5     Marcus Smart   20  BOS    0.0      6.0      650  0.009  67  27.0
 5     6     Jusuf Nurkić   20  DEN    0.0      3.0      650  0.005  62  17.8
 6     7  Jordan Clarkson   22  LAL    0.0      2.0      650  0.003  59  25.0

    ...  TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  ...  4.6  2.1  1.0  0.6  0.437  0.310  0.760  2.1  0.034  2015
 1  ...  4.9  1.2  0.7  0.7  0.405  0.316  0.803  5.7  0.165  2015
 2  ...  8.1  1.7  1.8  1.9  0.462    NaN  0.609  4.0  0.083  2015
 3  ...  4.3  6.5  1.7  0.2  0.425  0.262  0.551  2.3  0.044  2015
 4  ...  3.3  3.1  1.5  0.3  0.367  0.335  0.646  2.9  0.077  2015
 5  ...  6.2  0.8  0.8  1.1  0.446  0.000  0.636  1.6  0.069  2015
 6  ...  3.2  3.5  0.9  0.2  0.448  0.314  0.829  2.4  0.078  2015

 [7 rows x 21 columns],
    Rank              Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0     1  Karl-Anthony Towns   20  MIN  130.0    650.0      650  1.000  82
 1     2  Kristaps Porziņģis   20  NYK    0.0    363.0      650  0.558  72
 2     3        Nikola Jokić   20  DEN    0.0     59.0      650  0.091  80
 3     4        Devin Booker   19  PHO    0.0     49.0      650  0.075  76
 4     5       Jahlil Okafor   20  PHI    0.0     34.0      650  0.052  53
 5     6     Justise Winslow   19  MIA    0.0      7.0      650  0.011  78
 6     7     Emmanuel Mudiay   19  DEN    0.0      4.0      650  0.006  68
 7     8        Myles Turner   19  IND    0.0      3.0      650  0.005  60
 8     9    D'Angelo Russell   19  LAL    0.0      1.0      650  0.002  80

      MP  ...   TRB  AST  STL  BLK    FG%    3P%    FT%   WS  WS/48  Year
 0  32.0  ...  10.5  2.0  0.7  1.7  0.542  0.341  0.811  8.3  0.151  2016
 1  28.4  ...   7.3  1.3  0.7  1.9  0.421  0.333  0.838  4.4  0.102  2016
 2  21.7  ...   7.0  2.4  1.0  0.6  0.512  0.333  0.811  6.7  0.185  2016
 3  27.7  ...   2.5  2.6  0.6  0.3  0.423  0.343  0.840  1.9  0.043  2016

In [33]:
roys = pd.concat(dfs)

In [34]:
roys = roys.iloc[1:]

In [35]:
roys

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
1,2,Yao Ming,22,HOU,45.0,405.0,585,0.692,82,29.0,...,8.2,1.7,0.4,1.8,0.498,0.500,0.811,8.7,0.176,2003
2,3,Caron Butler,22,MIA,13.0,179.0,585,0.306,78,36.6,...,5.1,2.7,1.8,0.4,0.416,0.318,0.824,5.1,0.086,2003
3,4,Manu Ginóbili,25,SAS,0.0,5.0,585,0.009,69,20.7,...,2.3,2.0,1.4,0.2,0.438,0.345,0.737,4.2,0.141,2003
4,5,Drew Gooden,21,TOT,0.0,3.0,585,0.005,70,26.8,...,6.5,1.2,0.8,0.5,0.457,0.292,0.712,1.7,0.043,2003
5,6,Nenê,20,DEN,0.0,2.0,585,0.003,80,28.2,...,6.1,1.9,1.6,0.8,0.519,0.000,0.578,5.0,0.107,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,2,Jalen Williams,21,OKC,0.0,241.0,500,0.482,75,30.3,...,4.5,3.3,1.4,0.5,0.521,0.356,0.812,5.6,0.119,2023
2,3,Walker Kessler,21,UTA,2.0,114.0,500,0.228,74,23.0,...,8.4,0.9,0.4,2.3,0.720,0.333,0.516,7.1,0.200,2023
3,4,Bennedict Mathurin,20,IND,0.0,27.0,500,0.054,78,28.5,...,4.1,1.5,0.6,0.2,0.434,0.323,0.828,1.8,0.038,2023
4,5,Keegan Murray,22,SAC,0.0,21.0,500,0.042,80,29.8,...,4.6,1.2,0.8,0.5,0.453,0.411,0.765,4.3,0.087,2023
5,6,Jaden Ivey,20,DET,0.0,3.0,500,0.006,74,31.1,...,3.9,5.2,0.8,0.2,0.416,0.343,0.747,0.0,-0.001,2023

In [36]:
roys.to_csv("roys.csv")

In [97]:
rookie_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_rookies.html"

url = rookie_stats_url.format(2003)
data = requests.get(url)
with open("rookie/2003.html", "w+", encoding="utf-8") as f:
    f.write(data.text)

In [39]:
!pip install selenium

Collecting selenium
  Obtaining dependency information for selenium from https://files.pythonhosted.org/packages/dc/72/96b5afa16908f9abc7c24b70adfd3a46c9740eb728ddfeab28379e38eaf9/selenium-4.16.0-py3-none-any.whl.metadata
  Downloading selenium-4.16.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\and2b\anaconda3\lib\site-packages (from selenium) (1.26.16)
Collecting trio~=0.17 (from selenium)
  Obtaining dependency information for trio~=0.17 from https://files.pythonhosted.org/packages/3e/14/746bb2b403af4be680ca0ae240d62473c4ec3b836024c2e85f27856d7991/trio-0.23.2-py3-none-any.whl.metadata
  Downloading trio-0.23.2-py3-none-any.whl.metadata (4.9 kB)
Collecting trio-websocket~=0.9 (from selenium)
  Obtaining dependency information for trio-websocket~=0.9 from https://files.pythonhosted.org/packages/48/be/a9ae5f50cad5b6f85bd2574c2c923730098530096e170c1ce7452394d7aa/trio_websocket-0.11.1-py3-none-any.whl.metadata
  Downloading trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\and2b\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: attrs>=20.1.0 in c:\users\and2b\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\and2b\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\and2b\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Collecting outcome (from trio~=0.17->selenium)
  Obtaining dependency information for outcome from https://files.pythonhosted.org/packages/55/8b/5ab7257531a5d830fc8000c476e63c935488d74609b50f9384a643ec0a62/outcome-1.3.0.post0-py2.py3-none-any.whl.metadata
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio~=0.17->selenium)
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Requirement already satisfied: cffi>=1.14 in c:\users\and2b\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\and2b\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\and2b\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ---------------------------------------- 0.0/58.3 kB ? eta -:--:--
     ---------------------------------------- 58.3/58.3 kB 1.5 MB/s eta 0:00:00
Downloading selenium-4.16.0-py3-none-any.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
    --------------------------------------- 0.1/10.0 MB 4.2 MB/s eta 0:00:03
   - -------------------------------------- 0.5/10.0 MB 6.0 MB/s eta 0:00:02
   ---- ----------------------------------- 1.1/10.0 MB 9.1 MB/s eta 0:00:01
   --------- ------------------------------ 2.4/10.0 MB 13.9 MB/s eta 0:00:01
   -------------- ------------------------- 3.6/10.0 MB 16.4 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/10.0 MB 18.7 MB/s eta 0:00:01
   ---------------------- ----------------- 5.6/10.0 MB 19.7 MB/s eta 0:00:01
   ------------------------ --------------- 6.1/10.0 MB 17.0 MB/s eta 0:00:01
   -------------------------------- ------- 8.0/10.0 MB 19.6 MB/s eta 0:00:01
   -------------------------------------- - 9.5/10.0 MB 21.7 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.0 MB 21.9 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 19.3 MB/s eta 0:00:00
Downloading trio-0.23.2-py3-none-any.whl (461 kB)
   ---------------------------------------- 0.0/461.6 kB ? eta -:--:--
   --------------------------------------- 461.6/461.6 kB 30.1 MB/s eta 0:00:00
Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Installing collected packages: sniffio, outcome, h11, wsproto, trio, trio-websocket, selenium
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.2.0
    Uninstalling sniffio-1.2.0:
      Successfully uninstalled sniffio-1.2.0
Successfully installed h11-0.14.0 outcome-1.3.0.post0 selenium-4.16.0 sniffio-1.3.0 trio-0.23.2 trio-websocket-0.11.1 wsproto-1.2.0

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/selenium/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/selenium/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/selenium/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/selenium/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/selenium/

In [98]:
from selenium import webdriver

In [99]:
driver=webdriver.Chrome()

In [100]:
import time

year = 2003
url = rookie_stats_url.format(year)

driver.get(url)
driver.execute_script("window.scrollTo(1,10000)")
time.sleep(2)

html = driver.page_source

In [103]:
with open("rookie/{}.html".format(year), "w+", encoding="utf-8") as f:
    f.write(html)

In [104]:
years = list(range(2003, 2024))

In [105]:
for year in years:
    url = rookie_stats_url.format(year)

    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)

    html = driver.page_source
    with open("rookie/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(html)

In [106]:
dfs = []
for year in years:
    with open("rookie/{}.html".format(year), encoding="utf-8") as f:
        page= f.read()

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_="over_header").decompose()
    rookie_table = soup.find_all(id="rookies")
    rookie = pd.read_html(str(rookie_table))[0]
    rookie["Year"] = year
    dfs.append(rookie)

In [107]:
rookies = pd.concat(dfs)

In [108]:
rookies

,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,PF,PTS,FG%,3P%,FT%,MP.1,PTS.1,TRB.1,AST.1,Year
0,1,Robert Archibald,"Nov 9, '02, MEM @ DEN",22,2,44,328,15,53,0,...,59,51,.283,NaN,.429,7.5,1.2,1.6,0.4,2003
1,2,Maceo Baston,"Feb 12, '03, TOR vs. ATL",27,4,105,831,106,172,3,...,140,286,.616,.375,.740,7.9,2.7,1.7,0.2,2003
2,3,Mike Batiste,"Nov 1, '02, MEM @ DET",25,1,75,1248,197,467,18,...,120,481,.422,.222,.784,16.6,6.4,3.4,0.7,2003
3,4,Lonny Baxter,"Nov 1, '02, CHI vs. NOH",24,4,162,1884,247,530,1,...,324,637,.466,.200,.657,11.6,3.9,2.9,0.2,2003
4,5,Carlos Boozer,"Oct 29, '02, CLE @ SAC",21,13,861,26901,5847,11221,1,...,2612,13976,.521,.071,.722,31.2,16.2,9.5,2.2,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,81,Jalen Williams,"Oct 19, '22, OKC @ MIN",21,2,105,3232,619,1182,113,...,272,1596,.524,.380,.819,30.8,15.2,4.3,3.5,2023
89,82,Jaylin Williams,"Oct 23, '22, OKC vs. MIN",20,2,77,1246,136,322,65,...,156,389,.422,.385,.754,16.2,5.1,4.3,1.5,2023
90,83,Jeenathan Williams,"Apr 2, '23, POR @ MIN",23,2,9,149,30,50,3,...,15,66,.600,.300,.600,16.6,7.3,1.7,1.3,2023
91,84,Mark Williams,"Oct 19, '22, CHO @ SAS",21,2,62,1336,258,402,0,...,144,629,.642,NaN,.702,21.5,10.1,7.9,0.6,2023
92,85,Vince Williams Jr.,"Oct 22, '22, MEM @ DAL",22,2,40,628,52,149,32,...,70,164,.349,.283,.824,15.7,4.1,3.5,1.1,2023

In [109]:
rookies.to_csv("rookies.csv")

In [76]:
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [84]:
years = list(range(2003, 2024))

In [82]:
for year in years:
    url = team_stats_url.format(year)

    data = requests.get(url)

    with open("team/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [90]:
dfs = []
for year in years:
    with open("team/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_="thead").decompose()
    team_table = soup.find_all(id="divs_standings_E")
    team = pd.read_html(str(team_table))[0]
    team["Year"] = year
    team["Team"] = team["Eastern Conference"]
    del team["Eastern Conference"]
    dfs.append(team)

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_="thead").decompose()
    team_table = soup.find_all(id="divs_standings_W")
    team = pd.read_html(str(team_table))[0]
    team["Year"] = year
    team["Team"] = team["Western Conference"]
    del team["Western Conference"]
    dfs.append(team)

In [91]:
teams = pd.concat(dfs)

In [92]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                   Team
0   49  33  .598     —   95.4   90.1   4.42  2003       New Jersey Nets*
1   48  34  .585   1.0   96.8   94.5   1.76  2003    Philadelphia 76ers*
2   44  38  .537   5.0   92.7   93.1  -0.75  2003        Boston Celtics*
3   42  40  .512   7.0   98.5   98.4  -0.39  2003         Orlando Magic*
4   37  45  .451  12.0   91.5   92.5  -1.47  2003     Washington Wizards
..  ..  ..   ...   ...    ...    ...    ...   ...                    ...
13  51  31  .622     —  116.9  113.0   3.60  2023     Memphis Grizzlies*
14  42  40  .512   9.0  114.4  112.5   1.63  2023  New Orleans Pelicans*
15  38  44  .463  13.0  114.2  114.1  -0.14  2023       Dallas Mavericks
16  22  60  .268  29.0  110.7  118.6  -7.62  2023        Houston Rockets
17  22  60  .268  29.0  113.0  123.1  -9.82  2023      San Antonio Spurs

[729 rows x 9 columns]

In [93]:
teams.to_csv("teams.csv")

In [110]:
dfs = []
with open("rookie/2024.html".format(year), encoding="utf-8") as f:
        page= f.read()

soup = BeautifulSoup(page, "html.parser")
soup.find('tr', class_="over_header").decompose()
rookie_table = soup.find_all(id="rookies")
rookie = pd.read_html(str(rookie_table))[0]
rookie["Year"] = year
dfs.append(rookie)

In [111]:
current_rookies = pd.concat(dfs)

In [112]:
current_rookies

,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,PF,PTS,FG%,3P%,FT%,MP.1,PTS.1,TRB.1,AST.1,Year
0,1,Ibou Badji,"Dec 26, '23, POR vs. SAC",21,1,5,65,5,7,0,...,18,13,.714,NaN,.750,13.0,2.6,4.0,0.4,2023
1,2,Amari Bailey,"Nov 12, '23, CHO @ NYK",19,1,2,11,2,6,0,...,0,5,.333,.000,.500,5.5,2.5,1.0,0.0,2023
2,3,Emoni Bates,"Oct 28, '23, CLE vs. IND",20,1,10,76,6,25,5,...,5,18,.240,.250,.500,7.6,1.8,1.0,0.6,2023
3,4,Jules Bernard,"Dec 8, '23, WAS @ BRK",24,1,2,10,1,5,0,...,1,2,.200,.000,NaN,5.0,1.0,0.5,0.5,2023
4,5,Onuralp Bitim,"Nov 4, '23, CHI @ DEN",24,1,1,3,0,0,0,...,0,0,NaN,NaN,NaN,3.0,0.0,0.0,0.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,76,Jarace Walker,"Oct 25, '23, IND vs. WAS",20,1,10,87,12,28,3,...,11,33,.429,.273,.857,8.7,3.3,1.2,1.1,2023
82,77,Cason Wallace,"Oct 25, '23, OKC @ CHI",20,1,33,712,89,166,35,...,58,229,.536,.432,.842,21.6,6.9,2.1,1.5,2023
83,78,Victor Wembanyama,"Oct 25, '23, SAS vs. DAL",20,1,30,879,214,477,44,...,69,575,.449,.291,.786,29.3,19.2,10.1,2.8,2023
84,79,Cam Whitmore,"Oct 25, '23, HOU @ ORL",19,1,9,88,25,46,9,...,9,66,.543,.429,.500,9.8,7.3,2.1,0.3,2023
85,80,Jalen Wilson,"Nov 1, '23, BRK @ MIA",23,1,11,104,16,32,2,...,9,49,.500,.250,1.000,9.5,4.5,2.2,0.8,2023

In [114]:
current_rookies.to_csv("current_rookies.csv")